media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    create: true
    delete: true
    view:
      fields: [name]
      sort_by: name
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
      
      - name: order
        label: Order
        type: number
        description: Optional numeric order for sorting
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: A short introduction text which will also be used as the description on the Style card
      
      - name: details
        label: Details
        type: text
        description: Optional detailed description
  
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    create: true
    delete: true
    view:
      fields: [name, photo]
      sort_by: name
      sort_direction: asc
    fields:
      - name: name
        label: Name
        type: string
        required: true
      
      - name: photo
        label: Photo
        type: image
        required: false
        description: A Photo of the Artist (optional)
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: A short introduction text which will also be used as the description on the artist card
      
      - name: body
        label: Main content
        type: rich-text
        description: Optional detailed description

