media:
  - name: images
    label: Images
    input: public/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    description: |
      Tattoo styles that artists work in (e.g., Linework, Blackwork, Neo Traditional).
      Each style has its own page and is used to tag works and filter artists.
    create: true
    delete: true
    view:
      fields: [order, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
        description: The display name shown on the website (e.g., "Traditional & Old School").
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: |
          URL identifier used in links (e.g., "traditional-and-old-school").
          Must be lowercase, use hyphens instead of spaces, and match the filename exactly.
      
      - name: order
        label: Display Order
        type: number
        description: |
          Controls the position in lists and carousels. Lower numbers appear first.
          Use decimals to insert between existing items (e.g., 1.5 between 1 and 2).
          Leave empty to sort alphabetically after ordered items.
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: |
          A 1-2 sentence description of the style. Shown on style cards in carousels
          and at the top of the style's page. Keep it concise and engaging.
      
      - name: details
        label: Extended Description
        type: text
        description: |
          Optional longer description with more details about the style's history,
          characteristics, or what makes it unique. Shown on the style's detail page.
  
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    description: |
      Studio artists with their profiles, photos, and Instagram links.
      Each artist has a dedicated page showing their bio and portfolio of works.
    create: true
    delete: true
    view:
      fields: [order, photo, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
        description: |
          The artist's display name as shown on the website (e.g., "Nastia Zlotin").
          Can include spaces, capitals, and special characters.
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: |
          URL identifier used in links (e.g., "nastia-zlotin" for nastia-zlotin.md).
          Must be lowercase with hyphens and match the filename exactly.
          IMPORTANT: This slug is also used to link works to this artist.
      
      - name: order
        label: Display Order
        type: number
        description: |
          Controls the position in artist lists and carousels. Lower numbers appear first.
          Use decimals to insert between existing items (e.g., 2.5 between 2 and 3).
          Leave empty to sort alphabetically after ordered items.
      
      - name: photo
        label: Profile Photo
        type: image
        required: false
        description: |
          Portrait photo of the artist. Displayed on artist cards and their profile page.
          Recommended: Square or 2:3 portrait ratio. High quality JPG or PNG.
      
      - name: intro
        label: Short Bio
        type: text
        required: true
        description: |
          A 1-3 sentence introduction. Shown on artist cards in carousels and
          at the top of their profile page. Focus on experience, specialty, and personality.
      
      - name: instagram
        label: Instagram Username
        type: string
        required: false
        description: |
          Instagram handle without the @ symbol (e.g., "arspunx" not "@arspunx").
          Creates a clickable link to their Instagram profile.
      
      - name: body
        label: Full Biography
        type: rich-text
        description: |
          Optional extended biography with rich formatting (bold, links, lists).
          Shown below the gallery on the artist's profile page. Tell their story,
          background, artistic journey, and what inspires them.
  
  # ============================================
  # WORKS
  # ============================================
  - name: works
    label: Works
    type: collection
    path: src/content/works
    description: |
      Portfolio of tattoo works organized by artist.
      
      ⚠️ IMPORTANT: Works must be placed in folders named after the artist's SLUG
      (not their display name). For example:
      • Artist "Nastia Zlotin" (slug: nastia-zlotin) → works go in: works/nastia-zlotin/
      • Artist "Alex" (slug: alex) → works go in: works/alex/
      
      The folder name must exactly match the artist's slug (filename without .md).
    create: true
    delete: true
    view:
      fields: [order, image]
      sort_by: order
      sort_direction: asc
    fields:
      - name: image
        label: Tattoo Image
        type: image
        required: true
        description: |
          High-quality photo of the finished tattoo work.
          Recommended: Good lighting, clean background, healed tattoo if possible.
          Supported formats: JPG, PNG, WebP.
      
      - name: styles
        label: Styles
        type: reference
        required: true
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: |
          Select all styles that describe this work. Multiple styles can be selected.
          These appear as tags on the image and link to the corresponding style pages.
      
      - name: order
        label: Display Order
        type: number
        description: |
          Controls the position in the artist's portfolio gallery. Lower numbers appear first.
          The first work (order: 1) is used as the preview image on artist cards.
          Leave empty to sort after ordered items.