media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  - name: styles
    label: Tattoo Styles
    type: collection
    path: src/content/styles
    extension: md
    create: true
    delete: true
    fields:
      - name: id
        type: uuid
        options:
          editable: false
      - name: name
        type: string
        required: true
      - name: slugOverride
        type: string
      - name: order
        type: number
      - name: intro
        type: text
        required: true
      - name: details
        type: rich-text
      - name: cover
        type: image

  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    extension: md
    create: true
    delete: true
    fields:
      - name: id
        type: uuid
        options:
          editable: false
      - name: name
        type: string
        required: true
      - name: slugOverride
        type: string
      - name: photo
        type: image
        required: true
      - name: intro
        type: text
        required: true
      - name: styles
        type: reference
        options:
          collection: styles
          multiple: true
          value: "{id}"
          label: "{name}"
      - name: details
        type: rich-text
      - name: works
        type: list
        fields:
          - name: image
            type: image
            required: true
          - name: styleTags
            type: reference
            options:
              collection: styles
              multiple: true
              value: "{id}"
              label: "{name}"
