media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    extension: md
    create: true
    delete: true
    view:
      fields: [name, order, intro, details, cover]
      primary: name
    fields:
      - name: id
        type: uuid
        ui:
          hidden: true
        options:
          editable: false
      - name: name
        type: string
        required: true
      - name: slugOverride
        type: string
      - name: order
        type: number
      - name: intro
        type: text
        required: true
      - name: details
        type: rich-text
      - name: cover
        type: image

  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    extension: md
    create: true
    delete: true
    view:
      fields: [name, photo, intro, styles, details]
      primary: name
    fields:
      - name: id
        type: uuid
        ui:
          hidden: true
        options:
          editable: false
      - name: name
        type: string
        required: true
      - name: slugOverride
        type: string
      - name: photo
        type: image
        required: true
      - name: intro
        type: text
        required: true
      - name: styles
        type: reference
        options:
          collection: styles
          multiple: true
          value: "{id}"
          label: "{name}"
        ui:
          listLabel: "{name}"
      - name: details
        type: rich-text

  - name: works
    label: Works
    type: collection
    path: src/content/works
    extension: md
    create: true
    delete: true
    view:
      fields: [image, styles, artist]
      primary: image
    fields:
      - name: id
        type: uuid
        ui:
          hidden: true
        options:
          editable: false
      - name: image
        label: Image
        type: image
        required: true
      - name: styles
        label: Styles
        type: reference
        options:
          collection: styles
          multiple: true
          value: "{id}"
          label: "{name}"
        ui:
          listLabel: "{name}"
      - name: artist
        label: Artist
        type: reference
        options:
          collection: artists
          multiple: false
          value: "{id}"
          label: "{name}"
        ui:
          listLabel: "{name}"