media:
  - name: images
    label: Images
    input: public/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]
  
  - name: videos
    label: Videos
    input: public/images/videos
    output: /images/videos
    extensions: [mp4, webm, mov]
    categories: [video]

content:
  # ============================================
  # HOMEPAGE
  # ============================================
  - name: homepage
    label: Homepage
    type: collection
    path: src/content/homepage
    create: false
    delete: false
    fields:
      # Hero Section
      - name: headline
        label: Hero Headline
        type: string
        required: true
        description: Main headline displayed in the hero section
      
      - name: introText
        label: Hero Introduction
        type: text
        required: true
        description: Introduction text below the headline. Use **text** for bold formatting.
      
      - name: videoSrc
        label: Hero Video
        type: image
        required: false
        options:
          input: public/images/videos
          output: /images/videos
        description: Background video for the hero section. Upload MP4 files here.
      
      - name: topRightImage
        label: Hero Top Right Image
        type: image
        required: false
        description: Decorative overlay image (top right)
      
      - name: bottomLeftImage
        label: Hero Bottom Left Image
        type: image
        required: false
        description: Decorative overlay image (bottom left)
      
      # Reviews Section
      - name: reviewsTitle
        label: Reviews Title
        type: string
        required: false
        description: Title for the reviews section
      
      - name: reviewsSubtitle
        label: Reviews Subtitle
        type: string
        required: false
        description: Subtitle for reviews. Use **text** for bold formatting.
      
      # Instagram Section
      - name: instagramTitle
        label: Instagram Title
        type: string
        required: false
        description: Title for the Instagram promo section
      
      - name: instagramHandle
        label: Instagram Handle
        type: string
        required: false
        description: Instagram handle with @ symbol (e.g., @highcontrasttattoo)
      
      - name: instagramUrl
        label: Instagram URL
        type: string
        required: false
        description: Full URL to Instagram profile
      
      - name: instagramBackgroundImage
        label: Instagram Background
        type: image
        required: false
        description: Background image for the Instagram section
      
      # Studio Section
      - name: studioTitle
        label: Studio Title
        type: string
        required: false
        description: Title for the studio gallery section
      
      - name: studioDescription
        label: Studio Description
        type: text
        required: false
        description: Description text for the studio section
      
      # Walk-In Section
      - name: walkInTitle
        label: Walk-In Title
        type: string
        required: false
        description: Title for the walk-in section
      
      - name: walkInDescription
        label: Walk-In Description
        type: string
        required: false
        description: Description for walk-in availability
      
      - name: walkInSchedule
        label: Walk-In Schedule
        type: string
        required: false
        description: Walk-in hours (e.g., Monday–Saturday, 11:30–15:00)
      
      - name: walkInBackgroundImage
        label: Walk-In Background
        type: image
        required: false
        description: Background image for the walk-in section
      
      # Styles Section
      - name: stylesTitle
        label: Styles Title
        type: string
        required: false
        description: Title for the styles carousel section
      
      - name: stylesDescription
        label: Styles Description
        type: text
        required: false
        description: Description for the styles section
      
      - name: stylesCtaText
        label: Styles Button Text
        type: string
        required: false
        description: Text for the "Explore all Styles" button
      
      # Values Section
      - name: valuesTitle
        label: Values Title
        type: string
        required: false
        description: Title for the values/approach section
      
      - name: valuesDescription
        label: Values Description
        type: text
        required: false
        description: Description of studio values and approach
      
      # Artists Section
      - name: artistsTitle
        label: Artists Title
        type: string
        required: false
        description: Title for the artists carousel section
      
      - name: artistsDescription
        label: Artists Description
        type: text
        required: false
        description: Description for the artists section
      
      - name: artistsCtaText
        label: Artists Button Text
        type: string
        required: false
        description: Text for the "Meet all our Artists" button

  # ============================================
  # SETTINGS
  # ============================================
  - name: settings
    label: Site Settings
    type: collection
    path: src/content/settings
    create: false
    delete: false
    fields:
      # Global
      - name: studioName
        label: Studio Name
        type: string
        required: false
        description: Studio name displayed in header and footer (default "High Contrast Tattoo")
      
      # Buttons
      - name: buttonBookSession
        label: Book Session Button
        type: string
        required: false
        description: Text for the booking button in the header and hero (default "Book a session")
      
      - name: buttonGoogleMaps
        label: Google Maps Button
        type: string
        required: false
        description: Text for Google Maps buttons throughout the site (default "Open in Google Maps")
      
      - name: buttonInstagram
        label: Instagram Button
        type: string
        required: false
        description: Text for Instagram buttons (default "See on Instagram")
      
      # Footer
      - name: footerHeadline
        label: Footer Headline
        type: string
        required: false
        description: Headline in the footer contact section
      
      - name: footerDescription
        label: Footer Description
        type: text
        required: false
        description: Description text in the footer
      
      - name: footerMapImage
        label: Footer Map Image
        type: image
        required: false
        description: Map image shown in the footer
      
      - name: footerEmailLabel
        label: Email Label
        type: string
        required: false
        description: Label for the email contact section
      
      - name: footerEmailDescription
        label: Email Description
        type: string
        required: false
        description: Description under the email label
      
      - name: footerPhoneLabel
        label: Phone Label
        type: string
        required: false
        description: Label for the phone contact section
      
      - name: footerPhoneDescription
        label: Phone Description
        type: string
        required: false
        description: Description under the phone label
      
      - name: footerStudioLabel
        label: Studio Label
        type: string
        required: false
        description: Label for the studio address section
      
      - name: footerEmail
        label: Email Address
        type: string
        required: false
        description: Contact email address
      
      - name: footerPhone
        label: Phone Number
        type: string
        required: false
        description: Contact phone number
      
      - name: footerWhatsAppUrl
        label: WhatsApp URL
        type: string
        required: false
        description: WhatsApp contact link (e.g., https://wa.me/4917672745645)
      
      - name: footerAddress
        label: Studio Address
        type: string
        required: false
        description: Full studio address
      
      - name: footerPrivacyNote
        label: Privacy Note
        type: string
        required: false
        description: Privacy/cookie notice text
      
      - name: footerCopyright
        label: Copyright Text
        type: string
        required: false
        description: Copyright notice (e.g., © 2026 High Contrast Tattoo)
      
      # Page Headers
      - name: artistsPageTitle
        label: Artists Page Title
        type: string
        required: false
        description: Header title for the Artists page (default: "Artists")
      
      - name: artistsPageDescription
        label: Artists Page Description
        type: text
        required: false
        description: Subheader/description text for the Artists page
      
      - name: stylesPageTitle
        label: Styles Page Title
        type: string
        required: false
        description: Header title for the Styles page (default: "Styles")
      
      - name: stylesPageDescription
        label: Styles Page Description
        type: text
        required: false
        description: Subheader/description text for the Styles page
  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    create: true
    delete: true
    view:
      fields: [order, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
        description: The name shown on the website (e.g., "Traditional & Old School")
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: URL identifier - lowercase with hyphens (e.g., "traditional-and-old-school"). Must match the filename.
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 1.5) to insert between items.
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: Short description shown on style cards and style pages. Keep it to 1-2 sentences.
      
      - name: body
        label: Extended Description
        type: rich-text
        description: Optional longer description with more details about the style. Supports rich text formatting.

      - name: cardImage
        label: Card Image
        type: image
        required: false
        description: Optional custom image for the style card on the front page. If not provided, an image from the Works collection will be used instead.
  
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    create: true
    delete: true
    view:
      fields: [order, photo, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
        description: The artist's name as shown on the website (e.g., "Nastia Zlotin")
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: "IMPORTANT: This slug must match the folder name where the artist's works are stored. For example, artist \"Nastia Zlotin\" uses slug \"nastia-zlotin\" and works go in folder \"works/nastia-zlotin/\". Use lowercase letters and hyphens (no spaces or capitals). This links works to the artist."
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 2.5) to insert between items.
      
      - name: photo
        label: Profile Photo
        type: image
        required: false
        description: Portrait photo shown on artist cards and profile pages
      
      - name: intro
        label: Short Bio
        type: text
        required: true
        description: Brief introduction shown on artist cards. 1-3 sentences about their experience and style.
      
      - name: instagram
        label: Instagram Username
        type: string
        required: false
        description: Instagram handle without @ symbol (e.g., "arspunx")

      - name: styles
        label: Styles
        type: reference
        required: false
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: Select the tattoo styles this artist specializes in. These styles will be displayed on the artist's profile page and listing. Multiple styles can be selected.
      
      - name: body
        label: Full Biography
        type: rich-text
        description: Optional longer biography with formatting. Shown on the artist's profile page below their gallery.
  
  # ============================================
  # WORKS
  # ============================================
  - name: works
    label: Works
    type: collection
    path: src/content/works
    create: true
    delete: true
    view:
      fields: [order, styles, image]
      sort_by: order
      sort_direction: asc
    fields:
      - name: image
        label: Tattoo Image
        type: image
        required: true
        description: Photo of the finished tattoo work
      
      - name: styles
        label: Styles
        type: reference
        required: true
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: Select all styles that apply to this work. Multiple can be selected.
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. The first work is used as preview on artist cards.
  
  # ============================================
  # REVIEWS
  # ============================================
  - name: reviews
    label: Reviews
    type: collection
    path: src/content/reviews
    create: true
    delete: true
    view:
      fields: [order, author, rating]
      sort_by: order
      sort_direction: asc
    fields:
      - name: rating
        label: Rating
        type: number
        required: false
        default: 5
        description: Star rating from 1 to 5 (default is 5)
      
      - name: author
        label: Author Name
        type: string
        required: true
        description: Name of the person who wrote the review
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 1.5) to insert between items.
      
      - name: body
        label: Review Text
        type: rich-text
        required: true
        description: The review content. The text will be displayed on the front page.
  
  # ============================================
  # STUDIO GALLERY
  # ============================================
  # This controls the "Inside the Studio" image gallery shown on the front page.
  # Add, remove, or reorder images to update the slideshow.
  - name: studio
    label: Studio Gallery
    type: collection
    path: src/content/studio
    create: false
    delete: false
    fields:
      - name: images
        label: Studio Images
        type: image
        options:
          multiple: true
          input: public/images/studio
          output: /images/studio
        required: true
        description: "These images appear in the \"Inside the Studio\" gallery on the front page. Drag images to change their order — the first image will appear first in the gallery."