media:
  - name: images
    label: Media
    input: public/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif, mp4]
    categories: [image]

content:
  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    create: true
    delete: true
    view:
      fields: [order, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
        description: The name shown on the website (e.g., "Traditional & Old School")
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: URL identifier - lowercase with hyphens (e.g., "traditional-and-old-school"). Must match the filename.
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 1.5) to insert between items.
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: Short description shown on style cards and style pages. Keep it to 1-2 sentences.
      
      - name: body
        label: Extended Description
        type: rich-text
        description: Optional longer description with more details about the style. Supports rich text formatting.
      
      - name: featuredImage
        label: Featured Image
        type: image
        required: false
        description: Optional featured image shown on style cards and style pages. If not provided, a default will be used.
      
      - name: accentColor
        label: Accent Color
        type: string
        required: false
        description: Hex color code for this style's accent color (e.g., "#954059"). Used for visual distinction.
      
      - name: icon
        label: Icon
        type: image
        required: false
        description: Optional icon or symbol representing this style. Should be a small, simple graphic.
  
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    create: true
    delete: true
    view:
      fields: [order, photo, name]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
        description: The artist's name as shown on the website (e.g., "Nastia Zlotin")
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: "IMPORTANT: This slug must match the folder name where the artist's works are stored. For example, artist \"Nastia Zlotin\" uses slug \"nastia-zlotin\" and works go in folder \"works/nastia-zlotin/\". Use lowercase letters and hyphens (no spaces or capitals). This links works to the artist."
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 2.5) to insert between items.
      
      - name: photo
        label: Profile Photo
        type: image
        required: false
        description: Portrait photo shown on artist cards and profile pages
      
      - name: intro
        label: Short Bio
        type: text
        required: true
        description: Brief introduction shown on artist cards. 1-3 sentences about their experience and style.
      
      - name: instagram
        label: Instagram Username
        type: string
        required: false
        description: Instagram handle without @ symbol (e.g., "arspunx")

      - name: styles
        label: Styles
        type: reference
        required: false
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: Select the tattoo styles this artist specializes in. These styles will be displayed on the artist's profile page and listing. Multiple styles can be selected.
      
      - name: body
        label: Full Biography
        type: rich-text
        description: Optional longer biography with formatting. Shown on the artist's profile page below their gallery.
  
  # ============================================
  # WORKS
  # ============================================
  - name: works
    label: Works
    type: collection
    path: src/content/works
    create: true
    delete: true
    view:
      fields: [order, styles, image]
      sort_by: order
      sort_direction: asc
    fields:
      - name: image
        label: Tattoo Image
        type: image
        required: true
        description: Photo of the finished tattoo work
      
      - name: styles
        label: Styles
        type: reference
        required: true
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: Select all styles that apply to this work. Multiple can be selected.
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. The first work is used as preview on artist cards.
  
  # ============================================
  # REVIEWS
  # ============================================
  - name: reviews
    label: Reviews
    type: collection
    path: src/content/reviews
    create: true
    delete: true
    view:
      fields: [order, author, rating]
      sort_by: order
      sort_direction: asc
    fields:
      - name: rating
        label: Rating
        type: number
        required: false
        default: 5
        description: Star rating from 1 to 5 (default is 5)
      
      - name: author
        label: Author Name
        type: string
        required: true
        description: Name of the person who wrote the review
      
      - name: order
        label: Order
        type: number
        description: Lower numbers appear first. Use decimals (like 1.5) to insert between items.
      
      - name: body
        label: Review Text
        type: rich-text
        required: true
        description: The review content. The text will be displayed on the front page.
  
  # ============================================
  # STUDIO GALLERY
  # ============================================
  # This controls the "Inside the Studio" image gallery shown on the front page.
  # Add, remove, or reorder images to update the slideshow.
  - name: studio
    label: Studio Gallery
    type: collection
    path: src/content/studio
    create: false
    delete: false
    fields:
      - name: images
        label: Studio Images
        type: image
        options:
          multiple: true
          input: public/images/studio
          output: /images/studio
        required: true
        description: "These images appear in the \"Inside the Studio\" gallery on the front page. Drag images to change their order — the first image will appear first in the gallery."