media: src/assets/images

content:
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: bio
        label: Short Bio
        type: text
        required: true
      - name: fullBio
        label: Full Bio
        type: text
      - name: image
        label: Profile Image
        type: image
        required: true
      - name: instagram
        label: Instagram Handle
        type: string
        required: true
      - name: tags
        label: Style Tags
        type: string
        list: true
      - name: bookingHref
        label: Booking Link
        type: string
        required: true
      - name: galleryImages
        label: Gallery Images
        type: object
        list: true
        fields:
          - name: src
            label: Image
            type: string
          - name: alt
            label: Alt Text
            type: string
      - name: contentBlocks
        label: Content Sections
        type: object
        list: true
        fields:
          - name: title
            label: Section Title
            type: string
          - name: paragraphs
            label: Paragraphs
            type: string
            list: true

  - name: styles
    label: Tattoo Styles
    type: collection
    path: src/content/styles
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: artists
        label: Artists
        type: object
        list: true
        fields:
          - name: name
            label: Artist Name
            type: string
          - name: href
            label: Artist Link
            type: string
      - name: bookingHref
        label: Booking Link
        type: string
        required: true
      - name: galleryImages
        label: Gallery Images
        type: object
        list: true
        fields:
          - name: src
            label: Image
            type: string
          - name: alt
            label: Alt Text
            type: string
      - name: contentBlocks
        label: Content Sections
        type: object
        list: true
        fields:
          - name: title
            label: Section Title
            type: string
          - name: paragraphs
            label: Paragraphs
            type: string
            list: true

  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Publish Date
        type: date
        required: true
      - name: thumbnail
        label: Featured Image
        type: image
      - name: body
        label: Content
        type: rich-text
