media:
  - name: images
    label: Images
    input: public/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Styles
    type: collection
    path: src/content/styles
    create: true
    delete: true
    view:
      fields: [name, order]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: URL-friendly identifier (e.g., "blackwork"). Must match the filename.
      
      - name: order
        label: Order
        type: number
        description: Optional. Lower numbers appear first. Supports decimals (e.g., 0.75). Items without order are sorted alphabetically.
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: A short introduction text which will also be used as the description on the Style card
      
      - name: details
        label: Details
        type: text
        description: Optional detailed description
  
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    create: true
    delete: true
    view:
      fields: [name, order, photo]
      sort_by: order
      sort_direction: asc
    fields:
      - name: name
        label: Name
        type: string
        required: true
      
      - name: slugOverride
        label: Slug
        type: string
        required: true
        description: URL-friendly identifier (e.g., "john-doe"). Must match the filename.
      
      - name: order
        label: Order
        type: number
        description: Optional. Lower numbers appear first. Supports decimals (e.g., 0.75). Items without order are sorted alphabetically.
      
      - name: photo
        label: Photo
        type: image
        required: false
        description: A Photo of the Artist (optional)
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: A short introduction text which will also be used as the description on the artist card
      
      - name: instagram
        label: Instagram Username
        type: string
        required: false
        description: Instagram username (without the @ symbol, e.g., "arspunx")
      
      - name: body
        label: Main content
        type: rich-text
        description: Optional detailed description
  
  # ============================================
  # WORKS
  # ============================================
  - name: works
    label: Works
    type: collection
    path: src/content/works
    create: true
    delete: true
    view:
      fields: [image, artist, order]
      sort_by: order
      sort_direction: asc
    fields:
      - name: image
        label: Tattoo Image
        type: image
        required: true
        description: Image of the tattoo work

      - name: artist
        label: Artist
        type: reference
        required: true
        options:
          collection: artists
          label: "{name}"
          value: "{slugOverride}"
          multiple: false
      
      - name: styles
        label: Styles
        type: reference
        required: true
        options:
          collection: styles
          label: "{name}"
          value: "{slugOverride}"
          multiple: true
        description: Select one or more styles that apply to this work
      
      - name: order
        label: Order
        type: number
        description: Optional. Lower numbers appear first. Supports decimals (e.g., 0.75). Items without order are sorted alphabetically.

