media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions: [jpg, jpeg, png, gif, svg, webp, avif]
    categories: [image]

content:
  # ============================================
  # ARTISTS
  # ============================================
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    extension: md
    create: true
    delete: true
    view:
      fields: [name]
      sort_by: name
      sort_direction: asc
    fields:
      - name: name
        label: Name
        type: string
        required: true
      
      - name: slugOverride
        label: Slug Override
        type: string
        description: Optional custom slug for the URL (defaults to filename)
      
      - name: photo
        label: Photo
        type: string
        required: true
        description: Path to the artist photo (e.g., /images/artist-placeholder.png)
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: Short introduction text
      
      - name: styles
        label: Styles
        type: string
        list: true
        required: true
        description: List of style slugs (e.g., linework, blackwork)
      
      - name: details
        label: Details
        type: text
        description: Optional detailed description (supports markdown)

  # ============================================
  # STYLES
  # ============================================
  - name: styles
    label: Tattoo Styles
    type: collection
    path: src/content/styles
    extension: md
    create: true
    delete: true
    view:
      fields: [name]
      sort_by: name
      sort_direction: asc
    fields:
      - name: name
        label: Style Name
        type: string
        required: true
      
      - name: slugOverride
        label: Slug Override
        type: string
        description: Optional custom slug for the URL (defaults to filename)
      
      - name: order
        label: Order
        type: number
        description: Optional numeric order for sorting
      
      - name: intro
        label: Introduction
        type: text
        required: true
        description: Short introduction text
      
      - name: details
        label: Details
        type: text
        description: Optional detailed description (supports markdown)

